# Quick introduction to NumPy and SciPy

## NumPy

In [1]:
import numpy as np

In [64]:
def print_ndarray_info(arr, name):
    print(f"{name} = {np.array_str(arr, precision=2, suppress_small=True)}, shape={arr.shape}, type={arr.dtype}")

### 1D arrays

In [65]:
v1 = np.array([1, 2, -5, 0, 7])
print_ndarray_info(v1, "v1")

v1 = [ 1  2 -5  0  7], shape=(5,), type=int64


In [66]:
v2 = np.array([2.5, 3.0, 0, -2, 1.25])
print_ndarray_info(v2, "v2")

v2 = [ 2.5   3.    0.   -2.    1.25], shape=(5,), type=float64


In [67]:
v3 = v1 + v2
print_ndarray_info(v3, "v3")

v3 = [ 3.5   5.   -5.   -2.    8.25], shape=(5,), type=float64


In [68]:
v4 = v1 * v2
print_ndarray_info(v4, "v4")

v4 = [ 2.5   6.   -0.   -0.    8.75], shape=(5,), type=float64


In [69]:
v5 = np.array([1, 2, 3])
v6 = v2 + v5

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [70]:
v6 = v4[:3]
print_ndarray_info(v5+v6, "v5+v6")

v5+v6 = [3.5 8.  3. ], shape=(3,), type=float64


In [71]:
a = np.dot(v5, v6)
print(f"v5⋅v6 = {a}")

v5⋅v6 = 14.5


### 2D arrays

In [72]:
M1 = np.array([
    [1, -1, 0],
    [0.5, 0, 2],
    [-2, 3, -0.5]
])
print_ndarray_info(M1, "M1")

M1 = [[ 1.  -1.   0. ]
 [ 0.5  0.   2. ]
 [-2.   3.  -0.5]], shape=(3, 3), type=float64


In [73]:
print(M1[0,0])
print(M1[2,1])

1.0
3.0


In [74]:
# first row
print(M1[0])

[ 1. -1.  0.]


In [75]:
# first column
print(M1[:, 0])

[ 1.   0.5 -2. ]


In [76]:
# transpose
print(M1.T)

[[ 1.   0.5 -2. ]
 [-1.   0.   3. ]
 [ 0.   2.  -0.5]]


In [77]:
# first row of M1.T == first col of M1
print(M1.T[0], M1[:, 0])

[ 1.   0.5 -2. ] [ 1.   0.5 -2. ]


In [78]:
# upper-left block of M1
print(M1[:2, :2])

[[ 1.  -1. ]
 [ 0.5  0. ]]


In [79]:
# Matrix-vector product (it's just another matrix-matrix product...)
v7 = np.dot(M1, v5)
print_ndarray_info(v7, "v7=M1⋅v5")

v7=M1⋅v5 = [-1.   6.5  2.5], shape=(3,), type=float64


In [80]:
# The order of multiplication matters!
np.dot(v5, M1)
# (in this case numpy considers v5 as a row vector)

array([-4. ,  8. ,  2.5])

In [81]:
# Matrix-Matrix product (remember: it's not commutative!)
M2 = np.array([[1, 2], [0, -1]])
M3 = np.array([[2, 0], [-1, 1]])
M4 = np.dot(M2, M3)
M5 = np.dot(M3, M2)
print_ndarray_info(M4, "M4=M2⋅M3")
print_ndarray_info(M5, "M5=M3⋅M2")

M4=M2⋅M3 = [[ 0  2]
 [ 1 -1]], shape=(2, 2), type=int64
M5=M3⋅M2 = [[ 2  4]
 [-1 -3]], shape=(2, 2), type=int64
